apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: angular-app-template
  title: Example Angular Template
  description: An example template for the scaffolder that creates a simple Angular application
  tags:
    - angular
    - frontend
    - template
spec:
  owner: admin
  type: website
  path: /templates/angular-app-template
  parameters:
    - title: Project Name
      description: Enter the name of your Angular project
      required: true
    - title: Description
      description: Enter a short description of your Angular app
      required: true
  steps:
    - id: fetch
      name: Fetch Template Repository
      action: fetch:template
      input:
        url: https://github.com/KalashniRob/backstage/edit/main/angular-app-template.yaml
        targetPath: .
    - id: write-angular-json
      name: Write angular.json
      action: write:file
      input:
        path: angular.json
        content: |
          {
            "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
            "version": 1,
            "newProjectRoot": "projects",
            "projects": {
              "angular-app": {
                "projectType": "application",
                "schematics": {},
                "root": "",
                "sourceRoot": "src",
                "prefix": "app",
                "architect": {
                  "build": {
                    "builder": "@angular-devkit/build-angular:application",
                    "options": {
                      "outputPath": "dist/angular-app",
                      "index": "src/index.html",
                      "browser": "src/main.ts",
                      "polyfills": ["zone.js"],
                      "tsConfig": "tsconfig.app.json",
                      "assets": ["src/favicon.ico", "src/assets"],
                      "styles": ["src/styles.css"],
                      "scripts": []
                    },
                    "configurations": {
                      "production": {
                        "budgets": [
                          {
                            "type": "initial",
                            "maximumWarning": "500kb",
                            "maximumError": "1mb"
                          },
                          {
                            "type": "anyComponentStyle",
                            "maximumWarning": "2kb",
                            "maximumError": "4kb"
                          }
                        ],
                        "outputHashing": "all"
                      },
                      "development": {
                        "optimization": false,
                        "extractLicenses": false,
                        "sourceMap": true
                      }
                    },
                    "defaultConfiguration": "production"
                  },
                  "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "configurations": {
                      "production": {
                        "buildTarget": "angular-app:build:production"
                      },
                      "development": {
                        "buildTarget": "angular-app:build:development"
                      }
                    },
                    "defaultConfiguration": "development"
                  },
                  "extract-i18n": {
                    "builder": "@angular-devkit/build-angular:extract-i18n",
                    "options": {
                      "buildTarget": "angular-app:build"
                    }
                  },
                  "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                      "polyfills": ["zone.js", "zone.js/testing"],
                      "tsConfig": "tsconfig.spec.json",
                      "assets": ["src/favicon.ico", "src/assets"],
                      "styles": ["src/styles.css"],
                      "scripts": []
                    }
                  }
                }
              }
            }
          }
    - id: write-package-lock
      name: Write package-lock.json
      action: write:file
      input:
        path: package-lock.json
        content: |
          {
            "name": "angular-app",
            "version": "0.0.0",
            "lockfileVersion": 3,
            "requires": true,
            "packages": {
              "": {
                "name": "angular-app",
                "version": "0.0.0",
                "dependencies": {
                  "@angular/animations": "^17.3.0",
                  "@angular/common": "^17.3.0",
                  "@angular/compiler": "^17.3.0",
                  "@angular/core": "^17.3.0",
                  "@angular/forms": "^17.3.0",
                  "@angular/platform-browser": "^17.3.0",
                  "@angular/platform-browser-dynamic": "^17.3.0",
                  "@angular/router": "^17.3.0",
                  "rxjs": "~7.8.0",
                  "tslib": "^2.3.0",
                  "zone.js": "~0.14.3"
                },
                "devDependencies": {
                  "@angular-devkit/build-angular": "^17.3.11",
                  "@angular/cli": "^17.3.11",
                  "@angular/compiler-cli": "^17.3.0",
                  "@types/jasmine": "~5.1.0",
                  "jasmine-core": "~5.1.0",
                  "karma": "~6.4.0",
                  "karma-chrome-launcher": "~3.2.0",
                  "karma-coverage": "~2.2.0",
                  "karma-jasmine": "~5.1.0",
                  "karma-jasmine-html-reporter": "~2.1.0",
                  "typescript": "~5.4.2"
                }
              }
            }
          }
    - id: log
      name: Log Success
      action: debug:log
      input:
        message: "Successfully wrote all required files for the Angular application."
