apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  description: Admin role
spec:
  type: team
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [KalashniRob]
